from django.urls import path
from .views import uetuni, ueuni, puuni, kcuni, ituuni, lcwuuni, gcuni, gccs, gcee, itucs, ituce, ituee, kccs, lcwuae, lcwucs, lcwucrp, lcwuee, lcwuse, punewbbit, punewce, punewcs, punewds, punewit, punewee, punewiem, punewenre, punewmme, punewpe, punewse, punewte, puoldcs, puoldds, puoldit, puoldse, uecs, ueit, uetdepts
from . import views
urlpatterns = [
    path('gcuni/', gcuni, name="gcuni"),
    path('uetuni/', uetuni, name="uetuni"),
    path('uetuni/<str:deptname>/', uetdepts, name="uetdepts"),
    path('ueuni/', ueuni, name="ueuni"),
    path('puuni/', puuni, name="puuni"),
    path('kcuni/', kcuni, name="kcuni"),
    path('lcwuuni/', lcwuuni, name="lcwuuni"),
    path('ituuni/', ituuni, name="ituuni"),
    path('gccs/', gccs, name="gccs"),
    path('gcee/', gcee, name="gcee"),
    path('itucs/', itucs, name="itucs"),
    path('ituce/', ituce, name="ituce"),
    path('ituee/', ituee, name="ituee"),
    path('kccs/', kccs, name="kccs"),
    path('lcwuae/', lcwuae, name="lcwuae"),
    path('lcwucs/', lcwucs, name="lcwucs"),
    path('lcwucrp/', lcwucrp, name="lcwucrp"),
    path('lcwuee/', lcwuee, name="lcwuee"),
    path('lcwuse/', lcwuse, name="lcwuse"),
    path('punewbbit/', punewbbit, name="punewbbit"),
    path('punewce/', punewce, name="punewce"),
    path('punewcs/', punewcs, name="punewcs"),
    path('punewds/', punewds, name="punewds"),
    path('punewit/', punewit, name="punewit"),
    path('punewee/', punewee, name="punewee"),
    path('punewiem/', punewiem, name="punewiem"),
    path('punewenre/', punewenre, name="punewenre"),
    path('punewmme/', punewmme, name="punewmme"),
    path('punewpe/', punewpe, name="punewpe"),
    path('punewse/', punewse, name="punewse"),
    path('punewte/', punewte, name="punewte"),
    path('puoldcs/', puoldcs, name="puoldcs"),
    path('puoldds/', puoldds, name="puoldds"),
    path('puoldit/', puoldit, name="puoldit"),
    path('puoldse/', puoldse, name="puoldse"),
    path('uecs/', uecs, name="uecs"),
    path('ueit/', ueit, name="ueit"),
]
   
