# Generated by Django 4.0.4 on 2022-06-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('merit_calculator', models.CharField(max_length=50)),
                ('eligibilty_criteria', models.CharField(max_length=100)),
                ('fee_structure', models.IntegerField()),
                ('merit_list', models.IntegerField()),
            ],
        ),
    ]
