# Generated by Django 4.0.4 on 2022-07-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='department',
            new_name='last_merit',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='merit_calculator',
            new_name='program_name',
        ),
        migrations.RemoveField(
            model_name='university',
            name='merit_list',
        ),
        migrations.AddField(
            model_name='university',
            name='university_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='university',
            name='eligibilty_criteria',
            field=models.CharField(max_length=1500),
        ),
    ]
